#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Move remaining junk emails using Microsoft Graph PowerShell SDK.
.DESCRIPTION
    Processes the remaining 19 messages from the 2026-03-15 junk email batch.
    Uses app-only certificate authentication.
#>

[CmdletBinding()]
param()

# Auth
Connect-MgGraph `
    -ClientId $env:DPB_GRAPH_CLIENT_ID `
    -TenantId $env:DPB_GRAPH_TENANT_ID `
    -CertificateThumbprint $env:DPB_GRAPH_CERT_THUMBPRINT `
    -NoWelcome

# Config
$userId = "58dba6be-24ef-4a75-b968-c64f75b504b1"
$DeletedItemsFolderId = "AAMkAGU4NTQ1NTVkLThiZGUtNDYwMC05N2FjLWIzZmU1Y2I5MjVjZQAuAAAAAAA8K5fYAynyTot_fsDj7yapAQD9YgbCLDoDRqbmmlLG6VOsAAAAAAEKAAA="

# Remaining 19 message IDs
$MessageIds = @(
    "AAMkAGU4NTQ1NTVkLThiZGUtNDYwMC05N2FjLWIzZmU1Y2I5MjVjZQBGAAAAAAA8K5fYAynyTot_fsDj7yapBwD9YgbCLDoDRqbmmlLG6VOsAAAASHvdAAD9YgbCLDoDRqbmmlLG6VOsAAgTAIajAAA=",
    "AAMkAGU4NTQ1NTVkLThiZGUtNDYwMC05N2FjLWIzZmU1Y2I5MjVjZQBGAAAAAAA8K5fYAynyTot_fsDj7yapBwD9YgbCLDoDRqbmmlLG6VOsAAAASHvdAAD9YgbCLDoDRqbmmlLG6VOsAAgTAIabAAA=",
    "AAMkAGU4NTQ1NTVkLThiZGUtNDYwMC05N2FjLWIzZmU1Y2I5MjVjZQBGAAAAAAA8K5fYAynyTot_fsDj7yapBwD9YgbCLDoDRqbmmlLG6VOsAAAASHvdAAD9YgbCLDoDRqbmmlLG6VOsAAgTAIaGAAA=",
    "AAMkAGU4NTQ1NTVkLThiZGUtNDYwMC05N2FjLWIzZmU1Y2I5MjVjZQBGAAAAAAA8K5fYAynyTot_fsDj7yapBwD9YgbCLDoDRqbmmlLG6VOsAAAASHvdAAD9YgbCLDoDRqbmmlLG6VOsAAgTAIaCAAA=",
    "AAMkAGU4NTQ1NTVkLThiZGUtNDYwMC05N2FjLWIzZmU1Y2I5MjVjZQBGAAAAAAA8K5fYAynyTot_fsDj7yapBwD9YgbCLDoDRqbmmlLG6VOsAAAASHvdAAD9YgbCLDoDRqbmmlLG6VOsAAgTAIZ2AAA=",
    "AAMkAGU4NTQ1NTVkLThiZGUtNDYwMC05N2FjLWIzZmU1Y2I5MjVjZQBGAAAAAAA8K5fYAynyTot_fsDj7yapBwD9YgbCLDoDRqbmmlLG6VOsAAAASHvdAAD9YgbCLDoDRqbmmlLG6VOsAAgTAIYrAAA=",
    "AAMkAGU4NTQ1NTVkLThiZGUtNDYwMC05N2FjLWIzZmU1Y2I5MjVjZQBGAAAAAAA8K5fYAynyTot_fsDj7yapBwD9YgbCLDoDRqbmmlLG6VOsAAAASHvdAAD9YgbCLDoDRqbmmlLG6VOsAAgTAIYoAAA=",
    "AAMkAGU4NTQ1NTVkLThiZGUtNDYwMC05N2FjLWIzZmU1Y2I5MjVjZQBGAAAAAAA8K5fYAynyTot_fsDj7yapBwD9YgbCLDoDRqbmmlLG6VOsAAAASHvdAAD9YgbCLDoDRqbmmlLG6VOsAAgTAIYnAAA=",
    "AAMkAGU4NTQ1NTVkLThiZGUtNDYwMC05N2FjLWIzZmU1Y2I5MjVjZQBGAAAAAAA8K5fYAynyTot_fsDj7yapBwD9YgbCLDoDRqbmmlLG6VOsAAAASHvdAAD9YgbCLDoDRqbmmlLG6VOsAAgTAIYIAAA=",
    "AAMkAGU4NTQ1NTVkLThiZGUtNDYwMC05N2FjLWIzZmU1Y2I5MjVjZQBGAAAAAAA8K5fYAynyTot_fsDj7yapBwD9YgbCLDoDRqbmmlLG6VOsAAAASHvdAAD9YgbCLDoDRqbmmlLG6VOsAAgTAIXvAAA=",
    "AAMkAGU4NTQ1NTVkLThiZGUtNDYwMC05N2FjLWIzZmU1Y2I5MjVjZQBGAAAAAAA8K5fYAynyTot_fsDj7yapBwD9YgbCLDoDRqbmmlLG6VOsAAAASHvdAAD9YgbCLDoDRqbmmlLG6VOsAAgTAIXtAAA=",
    "AAMkAGU4NTQ1NTVkLThiZGUtNDYwMC05N2FjLWIzZmU1Y2I5MjVjZQBGAAAAAAA8K5fYAynyTot_fsDj7yapBwD9YgbCLDoDRqbmmlLG6VOsAAAASHvdAAD9YgbCLDoDRqbmmlLG6VOsAAgTAIXfAAA=",
    "AAMkAGU4NTQ1NTVkLThiZGUtNDYwMC05N2FjLWIzZmU1Y2I5MjVjZQBGAAAAAAA8K5fYAynyTot_fsDj7yapBwD9YgbCLDoDRqbmmlLG6VOsAAAASHvdAAD9YgbCLDoDRqbmmlLG6VOsAAgTAIXXAAA=",
    "AAMkAGU4NTQ1NTVkLThiZGUtNDYwMC05N2FjLWIzZmU1Y2I5MjVjZQBGAAAAAAA8K5fYAynyTot_fsDj7yapBwD9YgbCLDoDRqbmmlLG6VOsAAAASHvdAAD9YgbCLDoDRqbmmlLG6VOsAAgSW4b4AAA=",
    "AAMkAGU4NTQ1NTVkLThiZGUtNDYwMC05N2FjLWIzZmU1Y2I5MjVjZQBGAAAAAAA8K5fYAynyTot_fsDj7yapBwD9YgbCLDoDRqbmmlLG6VOsAAAASHvdAAD9YgbCLDoDRqbmmlLG6VOsAAgSW4beAAA=",
    "AAMkAGU4NTQ1NTVkLThiZGUtNDYwMC05N2FjLWIzZmU1Y2I5MjVjZQBGAAAAAAA8K5fYAynyTot_fsDj7yapBwD9YgbCLDoDRqbmmlLG6VOsAAAASHvdAAD9YgbCLDoDRqbmmlLG6VOsAAgRpIIYAAA=",
    "AAMkAGU4NTQ1NTVkLThiZGUtNDYwMC05N2FjLWIzZmU1Y2I5MjVjZQBGAAAAAAA8K5fYAynyTot_fsDj7yapBwD9YgbCLDoDRqbmmlLG6VOsAAAASHvdAAD9YgbCLDoDRqbmmlLG6VOsAAgRpIITAAA=",
    "AAMkAGU4NTQ1NTVkLThiZGUtNDYwMC05N2FjLWIzZmU1Y2I5MjVjZQBGAAAAAAA8K5fYAynyTot_fsDj7yapBwD9YgbCLDoDRqbmmlLG6VOsAAAASHvdAAD9YgbCLDoDRqbmmlLG6VOsAAfxyUP8AAA=",
    "AAMkAGU4NTQ1NTVkLThiZGUtNDYwMC05N2FjLWIzZmU1Y2I5MjVjZQBGAAAAAAA8K5fYAynyTot_fsDj7yapBwD9YgbCLDoDRqbmmlLG6VOsAAAASHvdAAD9YgbCLDoDRqbmmlLG6VOsAAgRpIIDAAA="
)

Write-Host "M365 JUNK MAIL CLEANUP (CLI MODE)" -ForegroundColor Cyan
Write-Host "Messages to process: $($MessageIds.Count)"

$success = 0
$fail = 0

foreach ($id in $MessageIds) {
    try {
        Move-MgUserMessage -UserId $userId -MessageId $id -DestinationId $DeletedItemsFolderId -ErrorAction Stop
        Write-Host "✓ Moved: $($id.Substring(0, 10))..." -ForegroundColor Green
        $success++
    } catch {
        Write-Host "✗ Failed: $($_.Exception.Message)" -ForegroundColor Red
        $fail++
    }
    Start-Sleep -Milliseconds 500
}

Write-Host "`nSummary: $success moved, $fail failed."
