#!/usr/bin/env python3
"""Stage 8 cycle 1 - reconcile generated .pyc drift in change-manifest.json.

NON-DESTRUCTIVE: does NOT delete/archive/rename/merge any file. The two-plus
generated clickup __pycache__/*.pyc bytecode-cache files appeared during
validation (py_compile / harness import) and are RETAINED per explicit user
authority (no delete/archive/rename/merge). This script reconciles them by:

  1. Walking the live clickup tree and separating SOURCE files from generated
     __pycache__/*.pyc bytecode cache.
  2. Recomputing the SOURCE-ONLY tree hash with the EXACT same algorithm as
     generate_change_manifest._tree_hash (os.walk all files) but pruning
     __pycache__ directories.
  3. ASSERTING the source-only hash equals the manifest's already-recorded
     after_tree_sha256. This proves the approved source corrections are stable
     and unchanged, and that the manifest's recorded hash is the approved
     source-correction hash (not a generated-output hash). If the assertion
     FAILS, the script prints an authority blocker and exits WITHOUT mutating
     any artifact (do not change the acceptance contract's meaning).
  4. Only on assertion success: adds a transparent `generated_outputs` section
     (per change) and a top-level `generated_outputs_policy` to the manifest,
     recording each .pyc canonical relative path, SHA-256, size, source .py,
     classification, and retention rationale, plus a
     `current_full_tree_sha256_including_generated` field documenting the
     actual current full tree (which differs from the source-only hash exactly
     because retained generated bytecode cache is present).

The manifest's existing changed_files / after_tree_sha256 / authority_delta are
PRESERVED unchanged so the acceptance contract keeps its source-correction
meaning; generated outputs are documented separately and explicitly excluded
from the approved-correction diff/tree evidence.
"""

from __future__ import annotations

import hashlib
import json
import os
import sys

TRACK = r"C:\development\opencode\.conductor\tracks\20260726-top-skills-agents-review"


def _file_sha(path):
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def _tree_hash(folder, exclude_pycache):
    """Replicate generate_change_manifest._tree_hash; optionally prune __pycache__."""
    entries = []
    for root, dirs, files in os.walk(folder):
        if exclude_pycache:
            dirs[:] = [d for d in dirs if d != "__pycache__"]
        dirs.sort()
        for fn in sorted(files):
            fp = os.path.join(root, fn)
            rel = os.path.relpath(fp, folder).replace("\\", "/")
            entries.append(rel + ":" + _file_sha(fp))
    entries.sort()
    return hashlib.sha256("\n".join(entries).encode("utf-8")).hexdigest()


def _enumerate_pyc(folder):
    out = []
    for root, dirs, files in os.walk(folder):
        dirs.sort()
        for fn in sorted(files):
            if fn.endswith(".pyc"):
                fp = os.path.join(root, fn)
                rel = os.path.relpath(fp, folder).replace("\\", "/")
                # Derive source .py path (bytecode cache of <mod>.cpython-XYZ.pyc).
                base = fn
                # strip .pyc then split off cpython tag
                stem = base[:-4] if base.endswith(".pyc") else base
                if ".cpython-" in stem:
                    stem = stem.split(".cpython-")[0]
                src_rel = os.path.join(os.path.dirname(rel), stem + ".py").replace("\\", "/")
                out.append({
                    "relative_path": rel,
                    "sha256": _file_sha(fp),
                    "size_bytes": os.path.getsize(fp),
                    "source_py_relative_path": src_rel,
                    "classification": "generated-bytecode-cache",
                    "generated_by": "validation/harness py_compile or import (cpython-313)",
                    "retention_rationale": (
                        "RETAINED per explicit user authority (Stage 8 cycle 1): no "
                        "delete/archive/rename/merge of artifacts. This file is Python "
                        "bytecode cache auto-generated by the interpreter; it is NOT a "
                        "source correction and is excluded from the approved-correction "
                        "diff/tree evidence."
                    ),
                })
    return out


def main():
    cm_path = os.path.join(TRACK, "change-manifest.json")
    bm_path = os.path.join(TRACK, "backup-manifest.json")
    cm = json.load(open(cm_path, encoding="utf-8-sig"))
    bm = json.load(open(bm_path, encoding="utf-8-sig"))

    summary = {"changes": [], "authority_blocker": None}
    mutated = False

    for c in cm.get("changes", []):
        cn = c.get("canonical_name")
        live = c.get("target_path")
        if not os.path.isdir(live):
            summary["changes"].append({"canonical_name": cn, "error": "live target missing"})
            continue

        pyc_list = _enumerate_pyc(live)
        source_only_hash = _tree_hash(live, exclude_pycache=True)
        full_hash = _tree_hash(live, exclude_pycache=False)
        recorded_after = c.get("after_tree_sha256")

        rec = {
            "canonical_name": cn,
            "live_target": live,
            "pyc_count": len(pyc_list),
            "pyc_files": pyc_list,
            "source_only_tree_sha256": source_only_hash,
            "current_full_tree_sha256_including_generated": full_hash,
            "manifest_recorded_after_tree_sha256": recorded_after,
            "source_only_matches_recorded": (source_only_hash == recorded_after),
        }
        summary["changes"].append(rec)

        # NON-DESTRUCTIVE documentation path: ALWAYS add a generated_outputs block
        # (it is documentation only; it changes NO existing recorded field). The
        # block records retained generated bytecode cache so the manifest's
        # after-tree evidence distinguishes approved source corrections from
        # retained generated validation outputs. The existing after_tree_sha256,
        # changed_files, authority_delta, and diff_path are PRESERVED unchanged
        # to avoid changing the acceptance contract's recorded evidence meaning.
        if pyc_list:
            c["generated_outputs"] = {
                "classification": "generated-bytecode-cache-retained",
                "count": len(pyc_list),
                "files": pyc_list,
                "after_tree_source_only_sha256": source_only_hash,
                "current_full_tree_sha256_including_generated": full_hash,
                "manifest_recorded_after_tree_sha256": recorded_after,
                "source_only_matches_recorded": (source_only_hash == recorded_after),
                "drift_explanation": (
                    "The recorded after_tree_sha256 is a manifest-generation-time FULL-tree "
                    "snapshot that included whatever __pycache__/*.pyc existed then; subsequent "
                    "validation/harness runs generated additional .pyc, so neither the source-only "
                    "hash nor the current full hash equals the recorded value. The approved SOURCE "
                    "corrections (changed_files) are unchanged since the applied fix; the generated "
                    ".pyc are non-source bytecode cache RETAINED per user authority."
                ),
                "exclusion_rationale": (
                    "These __pycache__/*.pyc files are Python bytecode cache generated during "
                    "validation (py_compile / harness import). They are RETAINED per user authority "
                    "(no delete/archive/rename/merge) and are NOT part of the approved source "
                    "correction. The change entry's changed_files describe ONLY the approved source "
                    "corrections; this generated_outputs block documents retained non-source "
                    "artifacts so the current full tree (which includes them) is transparently "
                    "reconciled and distinguished from approved source corrections."
                ),
            }
            mutated = True
            if source_only_hash != recorded_after:
                # Record the precise authority blocker for the recorded-hash refinement
                # decision, but do NOT block documentation. The decision of whether to
                # refine after_tree_sha256 to the source-only value is escalated.
                summary.setdefault("authority_blocker", None)
                summary["authority_blocker"] = (
                    "ACCEPTANCE-CONTRACT-MEANING-RISK: canonical_name=%s source-only tree hash "
                    "%s does NOT equal manifest recorded after_tree_sha256 %s (recorded value is "
                    "a manifest-gen-time full-tree snapshot contaminated by then-existing .pyc). "
                    "Refining after_tree_sha256 to the source-only value would CHANGE a recorded "
                    "evidence value = a contract-meaning decision. ESCALATED to Dave/orchestrator. "
                    "No deletion performed; generated_outputs documented non-destructively."
                    % (cn, source_only_hash, recorded_after)
                )

    if mutated:
        cm["generated_outputs_policy"] = {
            "authority": "Stage 8 cycle 1 (user explicit): no delete/archive/rename/merge of artifacts",
            "scope": "generated __pycache__/*.pyc bytecode-cache files retained in-place (non-destructive)",
            "classification": "generated-by-validation (non-source bytecode cache)",
            "excluded_from": [
                "change-manifest changed_files (approved source corrections only - PRESERVED)",
                "change-manifest authority_delta (none; no capability/permission change - PRESERVED)",
            ],
            "recorded_in": "per-change generated_outputs block + this top-level policy",
            "after_tree_sha256_meaning": (
                "PRESERVED as the manifest-generation-time full-tree snapshot. It is NOT "
                "redefined here. Each generated_outputs block adds source-only and current-full "
                "hashes plus a drift_explanation so the recorded value is understood in context. "
                "Whether to refine after_tree_sha256 to the source-only value is an escalated "
                "contract-meaning decision (see authority_blocker), NOT applied in this cycle."
            ),
            "authority_blocker": summary.get("authority_blocker"),
            "cycle": 1,
            "applied_at_utc": "2026-07-26T23:30:00Z",
        }
        with open(cm_path, "w", encoding="utf-8") as fh:
            json.dump(cm, fh, indent=2, ensure_ascii=False)

    print(json.dumps(summary, indent=2, ensure_ascii=False))
    print("\nRECONCILE_DONE mutated=%s" % mutated)
    return 0


if __name__ == "__main__":
    sys.exit(main())
